# Generated by Django 5.0.2 on 2024-05-14 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_empresa', models.CharField(max_length=100)),
                ('pathbase', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
        ),
    ]
